/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RetrieveSearchRouteImport } from './routes/retrieve/search'
import { Route as RetrieveProjectsRouteImport } from './routes/retrieve/projects'
import { Route as RetrieveComposeRouteImport } from './routes/retrieve/compose'
import { Route as RetrieveChatRouteImport } from './routes/retrieve/chat'
import { Route as CaptureThinkingRouteImport } from './routes/capture/thinking'
import { Route as CaptureStudyRouteImport } from './routes/capture/study'
import { Route as CaptureDialogueRouteImport } from './routes/capture/dialogue'
import { Route as CaptureCurationRouteImport } from './routes/capture/curation'
import { Route as CaptureConversationRouteImport } from './routes/capture/conversation'
import { Route as CaptureBrowsingRouteImport } from './routes/capture/browsing'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RetrieveSearchRoute = RetrieveSearchRouteImport.update({
  id: '/retrieve/search',
  path: '/retrieve/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RetrieveProjectsRoute = RetrieveProjectsRouteImport.update({
  id: '/retrieve/projects',
  path: '/retrieve/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const RetrieveComposeRoute = RetrieveComposeRouteImport.update({
  id: '/retrieve/compose',
  path: '/retrieve/compose',
  getParentRoute: () => rootRouteImport,
} as any)
const RetrieveChatRoute = RetrieveChatRouteImport.update({
  id: '/retrieve/chat',
  path: '/retrieve/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureThinkingRoute = CaptureThinkingRouteImport.update({
  id: '/capture/thinking',
  path: '/capture/thinking',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureStudyRoute = CaptureStudyRouteImport.update({
  id: '/capture/study',
  path: '/capture/study',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureDialogueRoute = CaptureDialogueRouteImport.update({
  id: '/capture/dialogue',
  path: '/capture/dialogue',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureCurationRoute = CaptureCurationRouteImport.update({
  id: '/capture/curation',
  path: '/capture/curation',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureConversationRoute = CaptureConversationRouteImport.update({
  id: '/capture/conversation',
  path: '/capture/conversation',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureBrowsingRoute = CaptureBrowsingRouteImport.update({
  id: '/capture/browsing',
  path: '/capture/browsing',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/capture/browsing': typeof CaptureBrowsingRoute
  '/capture/conversation': typeof CaptureConversationRoute
  '/capture/curation': typeof CaptureCurationRoute
  '/capture/dialogue': typeof CaptureDialogueRoute
  '/capture/study': typeof CaptureStudyRoute
  '/capture/thinking': typeof CaptureThinkingRoute
  '/retrieve/chat': typeof RetrieveChatRoute
  '/retrieve/compose': typeof RetrieveComposeRoute
  '/retrieve/projects': typeof RetrieveProjectsRoute
  '/retrieve/search': typeof RetrieveSearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/capture/browsing': typeof CaptureBrowsingRoute
  '/capture/conversation': typeof CaptureConversationRoute
  '/capture/curation': typeof CaptureCurationRoute
  '/capture/dialogue': typeof CaptureDialogueRoute
  '/capture/study': typeof CaptureStudyRoute
  '/capture/thinking': typeof CaptureThinkingRoute
  '/retrieve/chat': typeof RetrieveChatRoute
  '/retrieve/compose': typeof RetrieveComposeRoute
  '/retrieve/projects': typeof RetrieveProjectsRoute
  '/retrieve/search': typeof RetrieveSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/capture/browsing': typeof CaptureBrowsingRoute
  '/capture/conversation': typeof CaptureConversationRoute
  '/capture/curation': typeof CaptureCurationRoute
  '/capture/dialogue': typeof CaptureDialogueRoute
  '/capture/study': typeof CaptureStudyRoute
  '/capture/thinking': typeof CaptureThinkingRoute
  '/retrieve/chat': typeof RetrieveChatRoute
  '/retrieve/compose': typeof RetrieveComposeRoute
  '/retrieve/projects': typeof RetrieveProjectsRoute
  '/retrieve/search': typeof RetrieveSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/capture/browsing'
    | '/capture/conversation'
    | '/capture/curation'
    | '/capture/dialogue'
    | '/capture/study'
    | '/capture/thinking'
    | '/retrieve/chat'
    | '/retrieve/compose'
    | '/retrieve/projects'
    | '/retrieve/search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/capture/browsing'
    | '/capture/conversation'
    | '/capture/curation'
    | '/capture/dialogue'
    | '/capture/study'
    | '/capture/thinking'
    | '/retrieve/chat'
    | '/retrieve/compose'
    | '/retrieve/projects'
    | '/retrieve/search'
  id:
    | '__root__'
    | '/'
    | '/capture/browsing'
    | '/capture/conversation'
    | '/capture/curation'
    | '/capture/dialogue'
    | '/capture/study'
    | '/capture/thinking'
    | '/retrieve/chat'
    | '/retrieve/compose'
    | '/retrieve/projects'
    | '/retrieve/search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaptureBrowsingRoute: typeof CaptureBrowsingRoute
  CaptureConversationRoute: typeof CaptureConversationRoute
  CaptureCurationRoute: typeof CaptureCurationRoute
  CaptureDialogueRoute: typeof CaptureDialogueRoute
  CaptureStudyRoute: typeof CaptureStudyRoute
  CaptureThinkingRoute: typeof CaptureThinkingRoute
  RetrieveChatRoute: typeof RetrieveChatRoute
  RetrieveComposeRoute: typeof RetrieveComposeRoute
  RetrieveProjectsRoute: typeof RetrieveProjectsRoute
  RetrieveSearchRoute: typeof RetrieveSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retrieve/search': {
      id: '/retrieve/search'
      path: '/retrieve/search'
      fullPath: '/retrieve/search'
      preLoaderRoute: typeof RetrieveSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retrieve/projects': {
      id: '/retrieve/projects'
      path: '/retrieve/projects'
      fullPath: '/retrieve/projects'
      preLoaderRoute: typeof RetrieveProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retrieve/compose': {
      id: '/retrieve/compose'
      path: '/retrieve/compose'
      fullPath: '/retrieve/compose'
      preLoaderRoute: typeof RetrieveComposeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retrieve/chat': {
      id: '/retrieve/chat'
      path: '/retrieve/chat'
      fullPath: '/retrieve/chat'
      preLoaderRoute: typeof RetrieveChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture/thinking': {
      id: '/capture/thinking'
      path: '/capture/thinking'
      fullPath: '/capture/thinking'
      preLoaderRoute: typeof CaptureThinkingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture/study': {
      id: '/capture/study'
      path: '/capture/study'
      fullPath: '/capture/study'
      preLoaderRoute: typeof CaptureStudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture/dialogue': {
      id: '/capture/dialogue'
      path: '/capture/dialogue'
      fullPath: '/capture/dialogue'
      preLoaderRoute: typeof CaptureDialogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture/curation': {
      id: '/capture/curation'
      path: '/capture/curation'
      fullPath: '/capture/curation'
      preLoaderRoute: typeof CaptureCurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture/conversation': {
      id: '/capture/conversation'
      path: '/capture/conversation'
      fullPath: '/capture/conversation'
      preLoaderRoute: typeof CaptureConversationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture/browsing': {
      id: '/capture/browsing'
      path: '/capture/browsing'
      fullPath: '/capture/browsing'
      preLoaderRoute: typeof CaptureBrowsingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaptureBrowsingRoute: CaptureBrowsingRoute,
  CaptureConversationRoute: CaptureConversationRoute,
  CaptureCurationRoute: CaptureCurationRoute,
  CaptureDialogueRoute: CaptureDialogueRoute,
  CaptureStudyRoute: CaptureStudyRoute,
  CaptureThinkingRoute: CaptureThinkingRoute,
  RetrieveChatRoute: RetrieveChatRoute,
  RetrieveComposeRoute: RetrieveComposeRoute,
  RetrieveProjectsRoute: RetrieveProjectsRoute,
  RetrieveSearchRoute: RetrieveSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
